spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/canil}
spring.datasource.username=${DATABASE_USERNAME:canil}
spring.datasource.password=${DATABASE_PASSWORD:canil}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

server.port=${SERVER_PORT:3000}

